Filter update
reportportal/client-net pull request #64
Opened 2020-12-21 16:02 UTC by mnicula

2020-12-22 18:24 UTC, nvborisenko commented on src/ReportPortal.Client/Abstractions/Requests/UpdateUserFilterRequest.cs
> +        /// list of parameters of selection
Should start from Upper case.

2020-12-22 18:25 UTC, nvborisenko commented on test/ReportPortal.Client.IntegrationTests/UserFilter/UserFilter.cs
> +        public async Task CreateGetUpdateDeleteUserFilter()
May I ask to create separate test to verify `Update` request only?

2020-12-22 18:27 UTC, nvborisenko requested changes
Thanks for the PR. Please fix inline comments. Correct token to make tests pass is `5c356bea-c2fb-4988-9a82-e63424859381`.

2021-01-11 08:42 UTC, mnicula commented
Done

2021-01-11 17:32 UTC, nvborisenko approved these changes

2021-01-11 17:33 UTC, merged